In [69]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

In [70]:
datasets=pd.read_csv("C://Users//basit//Downloads/creditcard.csv")
datasets.head(3)

   Time        V1        V2        V3        V4        V5  ...       V25       V26       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  ...  0.128539 -0.189115  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018  ...  0.167170  0.125895 -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  ... -0.327642 -0.139097 -0.055353 -0.059752  378.66      0

[3 rows x 31 columns]

In [71]:
datasets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [72]:
datasets.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [73]:
datasets["Class"].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [74]:
legit = datasets[datasets.Class == 0]
fraud = datasets[datasets.Class == 1]

In [75]:
legit.shape

(284315, 31)

In [76]:
fraud.shape

(492, 31)

In [77]:
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [78]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [79]:
datasets.groupby('Class').mean()

               Time        V1        V2        V3        V4  ...       V25       V26       V27       V28      Amount
Class                                                        ...
0      94838.202258  0.008258 -0.006271  0.012171 -0.007860  ... -0.000072 -0.000089 -0.000295 -0.000131   88.291022
1      80746.806911 -4.771948  3.623778 -7.033281  4.542029  ...  0.041449  0.051648  0.170575  0.075667  122.211321

[2 rows x 30 columns]

In [80]:
legit_sample = legit.sample(n=492)

In [81]:
new_datasets = pd.concat([legit_sample, fraud], axis=0)

In [82]:
new_datasets

            Time        V1        V2        V3        V4  ...       V26       V27       V28  Amount  Class
175122  122203.0  2.342682 -1.246354 -1.317609 -1.749839  ... -0.153646  0.014882 -0.047952   20.00      0
165230  117293.0 -3.566279  3.554294  0.940725  1.900181  ... -0.039303  0.672407  0.364099   22.76      0
128218   78639.0 -2.347975  1.100521  0.406567  1.597649  ... -0.767038 -0.404407 -0.121693   56.22      0
61081    49650.0 -0.836638  0.913579  0.977420 -1.639743  ...  0.788990  0.396174  0.163243    3.84      0
188419  127964.0 -1.074179  1.184745  0.559081 -0.783285  ...  0.306884  0.126911  0.112408    0.89      0
...          ...       ...       ...       ...       ...  ...       ...       ...       ...     ...    ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293  ...  0.788395  0.292680  0.147968  390.00      1
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  ...  0.739467  0.389152  0.186637    0.76      1
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308  ...  0.471111  0.385107  0.194361   77.89      1
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092  ...  0.606116  0.884876 -0.253700  245.00      1
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  ... -0.289617  0.002988 -0.015309   42.53      1

[984 rows x 31 columns]

In [83]:
new_datasets['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [84]:
new_datasets.groupby('Class').mean()

               Time        V1        V2        V3        V4  ...       V25       V26       V27       V28      Amount
Class                                                        ...
0      96898.621951  0.100158 -0.117738 -0.072374 -0.104372  ...  0.040132 -0.006344 -0.009821 -0.009613   91.849370
1      80746.806911 -4.771948  3.623778 -7.033281  4.542029  ...  0.041449  0.051648  0.170575  0.075667  122.211321

[2 rows x 30 columns]

In [85]:
x = new_datasets.drop(columns='Class',axis=1)
y = new_datasets['Class']

In [86]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [87]:
li = LinearRegression()

In [88]:
li.fit(x_train,y_train)

LinearRegression()

In [89]:
x_train_prediction = li.predict(x_train)

x_train_prediction_rounded = x_train_prediction.round().astype(int)

datasets_accuracy = accuracy_score(x_train_prediction_rounded, y_train)

print(f"Accuracy (rounded): {datasets_accuracy}")

Accuracy (rounded): 0.9237611181702668

In [90]:
x_test_prediction = li.predict(x_test)

x_test_prediction_rounded = x_train_prediction.round().astype(int)

datasets_accuracy = accuracy_score(x_train_prediction_rounded, y_train)

print(f"Accuracy (rounded): {datasets_accuracy}")

Accuracy (rounded): 0.9237611181702668

In [91]:
# li.score(x_test,y_test)

In [92]:
# li.score(x_train,y_train)